### ISSUE TITLE
Missing install.xml file

### ISSUE THREAD

**Issue by mherger** [philippe44/ShairTunes2#1]
Hi philippe44 - tried to run the plugin from a clone, rather than from the plugin download page. But it's missing the install.xml file.

**Comment by philippe44** [comment]
Hi Michael – That’s corrected now

From: mherger 
Sent: Thursday, August 25, 2016 1:31 AM
To: philippe44/ShairTunes2 
Subject: [philippe44/ShairTunes2] Missing install.xml file (#1)

Hi philippe44 - tried to run the plugin from a clone, rather than from the plugin download page. But it's missing the install.xml file.
