### ISSUE TITLE
Unable to play stream when flac is disabled

### ISSUE THREAD

**Issue by ronluna** [philippe44/ShairTunes2#12]
Wondering what would be the best way to play airplay streams without FLAC. The reason why I'm trying to disable flac is to prevent some flickering/glitches noise while playing the airplay stream. 

I've tried removing the checkmark from "Use Flac for streaming" but the server is unable to play the track. I thought the server would simple use PCM to play it but that was not the case. 

the logs shows:
[17-10-30 15:12:58.1520] Slim::Player::Song::open (530) Warning: Don't know how to handle content for [airplay://10.1.10.21:55431/be2c5ddc8dc925e80cdd2909f2b045a9_stream.flc] type: audio/wav

Any ideas?

**Comment by philippe44** [comment]
Have you tried the latest 0.81.0 version? I corrected a few things wrt wav playback. Also, what are these glitches? I'm afraid flac or wav will not change anything here. You might have small crack from time to time due to skipping or adding a block of frames for maintaining the same level of production/consumption of frames.

**Comment by ronluna** [comment]
Yes, I'm currently on version 0.81.0. and most likely you are right regarding the small crack . I figured by not transcoding to flac it might help a little. Although We won''t know if it helps as the plugin does not know what to do with the stream when flac is disabled. 

Is it working on your in just fine?

**Comment by philippe44** [comment]
What player are you trying to send the audio to? There is a few issues with wav transcoding, though. But the log you showed is still strange because the stream extension says "flc" althought the mime-type is properly set to "audio/wav". I looked at the code a few seconds ago and this should not happen.

**Comment by ronluna** [comment]
squeezelite-1.8.5 is the current version I'm trying to send the stream to.

**Comment by philippe44** [comment]
As usual, I did a last minute change that I should have had no impact, but was wrong ... anyway 0.81.1 should now work properly without flac. it will not change the small cracks problem, though

**Comment by philippe44** [comment]
THere is now an option (-r) to remove the cracks - see README
