### ISSUE TITLE
a full AirPlay and AirPlay 2 support?

### ISSUE THREAD

**Issue by Neustradamus** [philippe44/ShairTunes2#24]
It is possible to have a full AirPlay and AirPlay 2 support?

**Comment by philippe44** [comment]
AirPlay2 has just been reversed engineered a couple of weeks ago  and anyway I'm not very motivated to write a plugin for it, as it might not bring anything additional

**Comment by Neustradamus** [comment]
@philippe44: What is your email address?
SF alias did not work...

**Comment by philippe44** [comment]
it should, but feel free to make public comments here

**Comment by Neustradamus** [comment]
philippe44ca@users.sourceforge.net
sfi-mx-3.v28.lw.sourceforge.com
Remote Server returned '550 5.1.351 Remote server returned unknown recipient or mailbox unavailable -> 550 unknown user'

**Comment by philippe44** [comment]
That's because you're not a sourceforge user. Try again now I've authorized non-SF users to send me mail

**Comment by Neustradamus** [comment]
@philippe44: There was an update for close this ticket?

**Comment by philippe44** [comment]
It's because I don't have intention for now to implement AirPlay 2

**Comment by opacey** [comment]
Taking this opportunity to say thanks so much @philippe44 for your work on ShairTunes2. I had tried and failed for ages to get something like this working (AirPlay -> Synology NAS hosted LMS) without success. Ever since ShairTunes has started working in that environment I use it all the time and have don for years now, as do visitors who otherwise can't easily play their stuff through the system. Many thanks!
